import Carrousel from '../carrousel/carrousel.js';
import CarrouselList from '../carrousel/carrouselList.js';
import Navbar from '../navbar/navbar.js';
import Project from '../project/project.js';
import Techno from '../techno/techno.js';
//import '../perso/perso.scss';

function Pro() {
    const projects = [];

    projects.push(<Project key='1' id='1' name='Formation VR' pics={4} folder='/formationvr/' ext={'png'} logos={[<Techno key='1' name='Unreal Engine' path='ue.png'></Techno>]} desc="Dans le cadre de mon alternance de développeur VR, j'ai participé au développement d'une application visant à montrer les possibilités de la VR dans le monde professionnel. Cette application, destinée principalement à de futurs potentiels clients, est composée de plusieurs modules de formation manuelle. Chaque module contient une suite d'instruction à réaliser, et montre les possibilités de la VR via des manipulations d'objets 3D, des interactions avec l'environnement, etc... Chaque module propose un thème, et simule donc des gestes et entraînements manuels avec une précision réaliste."></Project>);
    projects.push(<Project key='2' id='2' name='Controle Pico' pics={3} folder='/pico/' ext={'png'} logos={[<Techno key='1' name='AndroidStudio' path='android.png'></Techno>, <Techno key='2' name='Java' path='java.png'></Techno>]} desc="Au cours de mon alternance, j'ai développé une application Android permettant de se connecter et de piloter un casque VR Pico G2. Depuis son téléphone, après une connection par Bluetooth, il est possible de lancer des applications sur le casque, de lancer des vidéos, et de contrôler le son et la luminosité du casque. Ce projet a été réalisé dans le but de pouvoir faire profiter différentes expériences VR à des personnes agées qui ne sont pas habituées à utiliser un casque VR ou des manettes."></Project>);
    projects.push(<Project key='3' id='3' name='Mini-jeux' pics={3} folder='/minijeux/' ext={'png'} logos={[<Techno key='1' name='AngularTS' path='angular.png'></Techno>]} desc="Suite à une demande client, j'ai réalisé un site web adapté pour mobile uniquement, constitué d'un parcours de 7 mini-jeux visant à sensibiliser des lycéens au gaspillage alimentaire et la consommation d'eau. J'ai donc participé à la création et au design des jeux, puis je les ai développé. J'ai dû également participer activement aux échanges avec les clients afin que le site et les jeux correspondent le mieux possible à leur vision."></Project>);
    projects.push(<Project key='4' id='4' name='CvTek' pics={4} folder='/cvtek/' ext={'png'} logos={[<Techno key='1' name='React' path='react.png'></Techno>, <Techno key='2' name='NodeJS' path='node.png'></Techno>, <Techno key='3' name='Express JS' path='express.png'></Techno>, <Techno key='4' name='MongoDB' path='mongo.svg'></Techno>]} desc="Durant ma première année en tant que pédago à Epitech, j'ai développé un POC d'une CVtèque. Le but de cette application web était de proposer aux étudiants un espace où ils pourraient upload leur CV à jour, accompagné de leurs compétences, ainsi que leurs critères de recherche d'alternance. Le staff, aurait ensuite accès à ces informations et pourrait s'en servir pour dynamiser la recherche d'alternance des apprenants."></Project>);
    projects.push(<Project key='5' id='5' name='Simulation Babysitter' pics={3} folder='/baby/' ext={'png'} logos={[<Techno key='1' name='Unreal Engine' path='ue.png'></Techno>]} desc="Mon dernier projet d'alternance consistait, à la demande d'un client, à réaliser une application VR proposant une série de mise en situation réelle d'un babysitter. J'ai donc participé à la conception des scénarios. Durant ce projet j'ai développé un smartphone utilisable dans l'appli pour appeler les secours, j'ai également intégré les différents modèles 3D ainsi que les animations nécessaires. J'ai également développé le système de scénario, ces derniers pouvant être réussi seulement sous certaines conditions."></Project>);
    projects.push(<Project key='6' id='6' name='MyRPG' pics={5} folder='/myrpg/' ext={'png'} logos={[<Techno key='1' name='C' path='c.png'></Techno>, <Techno key='2' name='SFML' path='sfml.png'></Techno>]} desc="MyRPG était mon dernier gros projet de ma première année d'étude. Le but était de développer un RPG en 2D, les consignes étant très basique (fonctionnalités basiques d'un RPG), les possibilités sur le projet étaient très vastes. Pour ce projet, j'ai décidé de développer mon propre moteur de jeu, très fortement inspiré de RPG Maker. J'ai donc créer un logiciel disposant d'une interface permettant de créer des maps, et d'y insérer des events comme des PNJ avec des dialogues ou encore des combats. J'ai également créer un système d'arbre de compétence, un inventaire, un système de quête, ainsi qu'un système de combat 3v3 en tour par tour."></Project>);
    projects.push(<Project key='7' id='7' name='ESP RTS' pics={0} folder='/esp/' ext={'png'} logos={[<Techno key='1' name='Unreal Engine' path='ue.png'></Techno>]} desc="Dans le cadre de mon projet libre de cursus en Master (ESP), j'ai réalisé un POC d'un jeu vidéo de style RTS, inspiré du jeu Starcraft. Le but principal de ce projet d'étude était de monter en compétence sur la gestion de projet. J'ai également pu monter en compétence sur la création d'un jeu multijoueur en ligne. Toute les fonctionnalités basiques d'un RTS étaient présentes, comme la gestion de ses unités, les combats, ou encore la création et utilisation de différents bâtiments."></Project>);

    return (
        <div id='perso-container'>
            <Navbar></Navbar>
            <Carrousel id={2}></Carrousel>
            {projects}
            <CarrouselList id={2}></CarrouselList>
        </div>
    )
}

export default Pro;