import Project from '../project/project.js';
import './perso.scss';
import Techno from '../techno/techno.js';
import Carrousel from '../carrousel/carrousel.js';
import Navbar from '../navbar/navbar.js';
import CarrouselList from '../carrousel/carrouselList.js';

function Perso() {
    const projects = [];

    projects.push(<Project key='1' id='1' name='Mad Cleaners' pics={10} folder='/madcleaners/' ext={'gif'} logos={[<Techno key='1' name='Unreal Engine' path='ue.svg'></Techno>]} desc="Mad Cleaners est un jeu vidéo d'horreur avec une touche décalée, jouable de 1 à 4 joueurs, ce jeu vous garanti une expérience pleine d'émotions entre amis. Vous incarnez une équipe de nettoyeurs embauchée par une mystérieuse entreprise qui a besoin de vous pour nettoyer des laboratoires secret dans lesquels des expériences ont mal tournées. Vous aurez un temps imparti pour mener à bien vos missions, et bien sûr, des créatures dangereuses essaieront de vous tuer. Gagner de l'expérience, un salaire, et équipez vous pour réussir des missions de plus en plus difficiles."></Project>);
    projects.push(<Project key='2' id='2' name='Marvel vs DC' pics={4} folder='/mvd/' ext={'png'} logos={[<Techno key='1' name='Unreal Engine' path='ue.svg'></Techno>]} desc="Marvel vs DC est un jeu de carte en ligne qui se joue en 1 contre 1. Le but est de construire son deck efficacement afin de réduire les points de vie de l'adversaire à 0. Il y a plusieurs type de carte, les cartes Personnage qui représentent des personnages des comics Marvel ou DC, ce sont des cartes que vous pouvez invoquer pour attaquer avec. Les cartes Magie vous aideront grâce à différents effets en jeu, et les cartes Equipement renforceront vos Personnages. Plus de 250 cartes sont disponnibles dans le jeu, et vous pouvez également personnaliser votre profil."></Project>);
    projects.push(<Project key='3' id='3' name='Pokemon Ultimate' pics={9} folder='/pu/' ext={'gif'} logos={[<Techno key='1' name='Rpg Maker' path='rpgmaker.png'></Techno>, <Techno key='2' name='Ruby' path='ruby.svg'></Techno>]} desc="Pokemon Ultimate est un fangame qui reprend presque tous les anciens Pokémons et personnages de la license officielle, et qui explore une toute nouvelle histoire. En parcourant une nouvelle région vous devrez affronter de nouveaux ennemies et récolter les 8 badges d'arène pour accéder à la ligue et devenir Maître Pokémon. De nouvelle mécanique vous attende également dans ce jeu pour les fans les plus assidus de la license."></Project>);
    projects.push(<Project key='4' id='4' name='Masteries Adventures' pics={5} folder='/masteries/' ext={'png'} logos={[<Techno key='1' name='React' path='react.png'></Techno>, <Techno key='2' name='NodeJS' path='node.png'></Techno>, <Techno key='3' name='Express JS' path='express.png'></Techno>]} desc="Afin d'apprendre à utiliser React, j'ai créer un site web utilisant l'API de Riot Games pour créer un mini-jeux sur League of Legends. Le concept reprend le système de maîtrise de champion de League of Legends et se base dessus pour vous faire jouer un personnage aléatoire selon vos maîtrises de champions. Une maîtrise de champion est un niveau qui augmente selon notre temps de jeu sur un personnage. Le but de Masteries Adventures est de monter tous les champions du jeu au niveau maximum de maîtrise. Pour ça, vous pouvez rechercher votre profil sur le site, visualiser vos maîtrises, puis le site vous proposera 3 champions aléatoires sur lesquels vous pouvez encore augmenter votre niveau. Choisissez-en un, et jouer le jusqu'à passer un nouveau niveau, avant de changer de champion."></Project>);
    projects.push(<Project key='5' id='5' name='The Awakens' pics={9} folder='/awakens/' ext={'png'} logos={[<Techno key='1' name='Unreal Engine' path='ue.svg'></Techno>]} desc="The Awakens est un projet de création d'un jeu vidéo solo indépendant de type Action-RPG Open world en 3D. Dans ce jeu, le joueur incarne un personnage dans un monde peuplé d'individus possédants des pouvoirs spécifiques, celui du héro, est de voler les pouvoirs des autres. J'ai créer ce projet en 2018, tout d'abord pour apprendre à utiliser Unreal Engine, mais également car c'est mon projet de rêve, bien que très ambitieux. J'ai donc créer tout un univers pour contextualiser le jeu, puis j'ai développé une bonne partie des systèmes du jeu de base pour en faire rapidement un POC. Aujourd'hui, tous les systèmes classiques d'un Action RPG sont présents, inventaire, crafting, compétences, PvE, équipements, montures, boss, dialogues, guildes, quêtes, ainsi que de nombreuses autres fonctionnalitées imaginées par mes soins."></Project>);
    projects.push(<Project key='6' id='6' name='MOBA Template' pics={1} folder='/moba/' ext={'png'} logos={[<Techno key='1' name='Unreal Engine' path='ue.svg'></Techno>]} desc="Peu après la sortie d'Unreal Engine 5, j'ai voulu expérimenter cette nouvelle version du moteur en créant un projet template pour les jeux de style MOBA, comme League of Legends. Le but est de proposer à n'importe qui un moyen de créer son MOBA rapidement en se servant des systèmes déjà implémentés dans mon template. Pour cela, j'ai dû créer les fonctionnalités basiques d'un MOBA, tout en développant le plus modulairement possible pour que n'importe qui puisse l'adapter selon ses besoins. J'ai donc créer un système de personnage, avec leurs statistiques, un système de compétences pouvant monter de niveau, une boutique avec un système d'équipement, un système d'expérience et d'argent, ainsi qu'un système de PvE avec des monstres, le tout en multijoueur."></Project>);
    projects.push(<Project key='7' id='7' name='The Tower' pics={1} folder='/tower/' ext={'png'} logos={[<Techno key='1' name='Unreal Engine' path='ue.svg'></Techno>]} desc="The Tower est un jeu de style Roguelite où vous incarnez un personnage qui doit gravir une tour remplie d'ennemies et de boss. Pour cela vous aurez accès à différentes armes que vous pouvez combiner et qui vous donne des compétences différentes. Pour gravir un étage de la tour vous devez battre tous les boss de l'étage. Divers surprises et loot sont disponnibles à travers chaques étages."></Project>);

    return (
        <div id='perso-container'>
            <Navbar></Navbar>
            <Carrousel id={2}></Carrousel>
            {projects}
            <CarrouselList id={2}></CarrouselList>
        </div>
    )
}

export default Perso;